name: Build and Run OpenAiCodeReview

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Set up JDK8
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '8'

      - name: Build with Maven
        run: mvn clean install

      - name: Copy openai-code-review-sdk JAR
        run: mvn dependency:copy -Dartifact=xyz.zhaokai:openai-code-review-sdk:1.0-SNAPSHOT -DoutputDirectory=./libs

      - name: Run Code Review
        run: java -jar ./libs/openai-code-review-sdk-1.0-SNAPSHOT.jar
      
