name: Build and Run OpenAiCodeReview

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Set up JDK8
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '8'

      - name: Build with Maven
        run: mvn clean install

      - name: Package with Maven
        run: mvn package

      - name: Run Code Review
        run: java -jar ./openai-code-review-sdk/target/openai-code-review-sdk-1.0-SNAPSHOT.jar
        env:
          GITHUB_TOKEN: ${{ secrets.CODE_TOKEN }}
