name: OpenAiCodeReview
on:
  push:
    branches:
      - '*'

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Set up JDK11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Run Java code
        run:
          cd openai-code-review-sdk/src/main/java/xyz/zhaokai/middleware/sdk
          javac OpenAiCodeReview.java
          java OpenAiCodeReview
